const express = require('express');
const app = express();

const cors = require('cors');
app.use(cors());
app.use(express.json());

//Task 2 solution
app.post('/event/:eventID/loc/:locID', (req, res) => {

    const event = req.params.eventID;
    const location = req.params.locID;
    const user = req.body.loginID;
  
    const message = `
    <html>
      <head>
        <title>Event information</title>
      </head>
      <body>
        <h1> You have logged in, this page is generated by the server </h1>
        <p> Below is the event information for you </p>
        <p>Event ID: ${event}</p>
        <p>Location: ${location}</p>
        <p>Login ID: ${user}</p>
      </body>
    </html>
    `;

    res.setHeader('Content-Type', 'text/html');
    res.send(message);
    
});
    

//Task 1 solution
/*
app.get('/event/:eventID/loc/:locID', (req, res) => {
    const data = req.params;
    let output = '';
  
    for (const key in data) {
      output += `${key}: ${data[key]}<br>`;
    }
  
    res.send(output);
  });
*/
const server = app.listen(3000);